services:
  # MySQL Database Service
  mysql:
    image: mysql:8.0
    container_name: mysql8_container
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: localdb
      MYSQL_USER: localuser
      MYSQL_PASSWORD: localpassword
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Django Service
  django:
    build:
      context: ./stack/django
      dockerfile: Dockerfile
    container_name: django-service
    volumes:
      - django-generated:/app/generated
      - $HOME/.ssl:/root/.ssl
      - ./stack/django/media:/app/django/media
    environment:
      DEBUG: "1"
      DJANGO_ENV: "development"
      DJANGO_DEBUG: "True"
    env_file:
      - ./stack/django/.env
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    extra_hosts:
      - "localapi.oaexample.com:127.0.0.1"

  # ReactJS Frontend Service
  reactjs:
    build:
      context: ./stack/reactjs
      dockerfile: Dockerfile
    container_name: reactjs-service
    volumes:
      - reactjs-generated:/app/generated
      - $HOME/.ssl:/root/.ssl
    depends_on:
      django:
        condition: service_started
    ports:
      - "3000:3000"
    extra_hosts:
      - "localhost.oaexample.com:127.0.0.1"

  fakedata:
    build:
      context: ./stack/databuilder
      dockerfile: Dockerfile
    container_name: fakedata-service
    depends_on:
      django:
        condition: service_started
    environment:
      PROJECTNAME: "${PROJECTNAME:-newproject}"
    command:
      - bash
      - "./fakedata.sh"
      - "--project"
      - "$PROJECTNAME"

volumes:
  django-generated:
  reactjs-generated:
  mysql-data:
