services:
  # MySQL Database Service
  mysql:
    image: mysql:8.0
    container_name: mysql8_container
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
#      - ./dockerized/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: localdb
      MYSQL_USER: localuser
      MYSQL_PASSWORD: localpassword
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Django Service
  django:
    build:
      context: ./stack/django
      dockerfile: Dockerfile
    container_name: django-service
    volumes:
      - $HOME/.ssl:/root/.ssl
#      - ./dockerized/django:/app/django
    #      - ./dockerized/django/media:/app/django/media  # Single, unified media directory
    environment:
      DEBUG: "1"
      DJANGO_ENV: "development"
      DJANGO_DEBUG: "True"
    env_file:
      - ./stack/django/.env
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    extra_hosts:
      - "localapi.oaexample.com:127.0.0.1"

  # ReactJS Frontend Service
  reactjs:
    build:
      context: ./stack/reactjs
      dockerfile: Dockerfile
    container_name: reactjs-service
    volumes:
#      - ./dockerized/reactjs:/app/reactjs
      - $HOME/.ssl:/root/.ssl
    depends_on:
      django:
        condition: service_started
    ports:
      - "3000:3000"
    extra_hosts:
      - "localhost.oaexample.com:127.0.0.1"

  # Fake data generator
  databuilder:
    build:
      context: ./stack/databuilder
      dockerfile: Dockerfile
    container_name: databuilder-service
#    volumes:
#      - ./dockerized/databuilder:/app/databuilder
    depends_on:
      django:
        condition: service_started
    environment:
      REACT_APP_API_HOST: "https://django-service:8080"  # Access Django API


  # Front-end end-to-end testing
  cypress:
    build:
      context: ./stack/cypress
      dockerfile: Dockerfile
    container_name: cypress-service
    env_file:
      - ./stack/cypress/.env
#    volumes:
#      - ./dockerized/cypress:/app/cypress
    depends_on:
      reactjs:
        condition: service_started
    environment:
      REACT_APP_APP_HOST: "https://reactjs-service:3000"  # Access ReactJS app during tests


volumes:
  mysql-data:
